// Generated by CoffeeScript 1.12.7
(function() {
  exports.clientApplication = "";

  exports.logControlPanel = "<a class=\"select_mode\" href=\"#log_control_streams\">Streams</a>\n<a class=\"select_mode active\" href=\"#log_control_nodes\">Nodes</a>";

  exports.logMessage = "<div>\n<span class='stream color<%= lmessage.get('stream').color %>'><%= lmessage.get('stream').id %></span>\n<span class='node color<%= lmessage.get('node').color %>'><%= lmessage.get('node').id %></span>\n<span class='level <%= level %>'><%= level %> </span>\n<span class='message <%= level %>'><%= msg %></span>\n<%  if (data) { %>\n  <pre class='data <%= level %> wrap'><%= data %></pre>\n<% } %>\n</div>";

  exports.logScreenView = "<div class='controls'>\n<% if (logScreens.length > 1) { %><a href=\"#\" class='close'>close</a><% } %>\n  <a href=\"#\" class='clear'>clear screen</a>\n  <a href=\"#\" class='clear-filter'>clear filter</a>\n  <a href=\"#\" class='filter'>filter <input type='text'/></a>\n</div>\n<div class='messages'>\n  <div class='msg'></div>\n</div>";

  exports.logScreensPanel = "<div class='log_screens tabs'></div>\n<div class='status_bar'>\n  <div class=\"tabbed\" id=\"tab_screen\">\n    <div class=\"tab-buttons\">\n    </div>\n  </div>\n  <a href=\"#\" class='button' id=\"new_screen_button\">New Screen</a>\n  <a href=\"#\" class='button' id=\"rename_screen_button\">Rename Screen</a>\n  <input id=\"rename_input\" placeholder=\"\" type=\"text\">\n\n  <div id=\"log_options\">\n    <label class=\"switch tooltip\">\n      <input type=\"checkbox\" checked name=\"stream\">\n      <span class=\"slider round\"></span>\n      <span class=\"tooltiptext\">Show Stream <br />Name</span>\n    </label>\n\n    <label class=\"switch tooltip\">\n      <input type=\"checkbox\" checked name=\"node\">\n      <span class=\"slider round\"></span>\n      <span class=\"tooltiptext\">Show Node <br />Name</span>\n    </label>\n\n    <label class=\"switch tooltip\">\n      <input type=\"checkbox\" checked name=\"level\">\n      <span class=\"slider round\"></span>\n      <span class=\"tooltiptext\">Show Level</span>\n    </label>\n\n    <label class=\"switch tooltip\">\n      <input type=\"checkbox\" checked name=\"time\">\n      <span class=\"slider round\"></span>\n      <span class=\"tooltiptext\">Show time</span>\n    </label>\n\n    <label class=\"switch tooltip\">\n      <input type=\"checkbox\" checked name=\"autoscroll\">\n      <span class=\"slider round\"></span>\n      <span class=\"tooltiptext\">Auto Scroll</span>\n    </label>\n  </div>\n  <div class='stats'></div>\n  <div style='clear: both;'</div>\n</div>";

  exports.logScreensTabButton = "<input type=\"radio\" name=\"tabs\" id=\"<%= cid %>\" <%= checked%>> <label for=\"<%= cid %>\" data-cid=\"<%= cid %>\"><%= name %></label>";

  exports.logStatsView = "<%\nvar elapsed = (new Date().getTime() - stats.start) / 1000;\nvar minutes = parseInt(elapsed/60);\nvar seconds = parseInt(elapsed%60);\nif (seconds < 10) { seconds = \"0\" + seconds; }\nvar prettyTime =  minutes + \":\" + seconds;\n%>\n<div class='stat'>\n  <span class='num'><%= (stats.messages / elapsed).toFixed(2) %></span>\n  <span class='label'>messages/sec</span>\n</div>\n<div class='stat'>\n  <span class='num'><%= prettyTime %></span>\n  <span class='label'>elapsed</span>\n</div>\n<div class='stat'>\n  <span class='num'><%= stats.messages %></span>\n  <span class='label'>Messages</span>\n</div>\n<div class='stat'>\n  <span class='num'><%= stats.nodes %></span>\n  <span class='label'>Nodes</span>\n</div>\n<div class='stat'>\n  <span class='num'><%= stats.streams %></span>\n  <span class='label'>Streams</span>\n</div>";

  exports.objectControls = "<input class='filter' placeholder=\"Filter...\" type='text'/>\n<div class='groups'></div>";

  exports.objectGroupControls = "<div class='items'></div>";

  exports.objectGroupHeader = "<div class='screen_buttons'>\n<% \nvar active = false;\nlogScreens.each(function(screen) {\n  var sactive = screen.isActive(object, getPair);\n  if (sactive) { active = true; }\n%>\n  <input type='checkbox' <% if (sactive) { %>checked=\"checked\" <% } %>title='screen-<%= screen.cid %>'/>\n<% }); %>\n</div>\n<div class='diode floatl <% if (active) { print('active color' + object.color) } %>'></div>\n<div class='object_name floatl'><%= object.get('name') %></div>\n<div style='clear: both;'></div>";

  exports.objectItemControls = "<div class='screen_buttons'>\n<% \nvar active = false;\nlogScreens.each(function(screen) {\n  var haspair = screen.hasPair(stream, node);\n  if (haspair) { active = true; }\n%>\n  <input type='checkbox' <% if (haspair) { %>checked='checked'<% } %>title='screen-<%= screen.cid %>'/>\n<% }); %>\n</div>\n<div class='diode floatl <% if (active) { print('active color' + item.color); } %>'></div>\n<div class='item_name floatl'><%= item.get('name') %></div>\n<div style='clear: both;'></div>";

}).call(this);
